---
- name: Capture kernel version
  set_fact:
    KERNEL_VERSION: "{{ ansible_kernel }}"

- name: verifying apt-packages state
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
    force: yes
  loop: "{{ apt_packages | flatten(levels=1) }}"
  when: apt_packages is defined and (apt_packages|length>0)

