---
- name: Server play
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  become_method: sudo
  vars:
    ansible_become_pass: "{{ ansible_sudo_pass }}"
  roles:
    - role: rke2_server
  serial: 1

- name: Agent play
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  become_method: sudo
  vars:
    ansible_become_pass: "{{ ansible_sudo_pass }}"
  roles:
    - role: rke2_agent
  serial: 3
