---
- name: Copy ssh-key from localhost to all hosts
  hosts: localhost
  roles:
    - role: ssh-copy-id

- name: Installing prerequisites on all hosts
  hosts: all
  become: yes
  roles:
    - role: apt-sources-list
    - role: apt-packages
    - role: ntp-client
    - role: disable-swap

- name: Provision gpu on gpu nodes only
  hosts: gpu_nodes
  become: yes
  roles:
   - role: nvidia-driver


- name: Server play
  hosts: rke2_servers
  any_errors_fatal: true
  become: yes
  roles:
    - role: rke2_server
  serial: 1

- name: Agent play
  hosts: rke2_agents
  any_errors_fatal: true
  become: yes
  roles:
    - role: rke2_agent
  serial: 3

# - name: Install Nvidia GPU Operator in the Cluster
#   hosts: gpu_nodes
#   become: yes
#   roles:
#    - role: nvidia-gpu-operator