---
- name: Use ssh-copy-id for all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy SSH key using ssh-copy-id
      command: ssh-copy-id {{ ansible_user }}@{{ inventory_hostname }}
      delegate_to: localhost
      ignore_errors: yes
      vars:
        ansible_ssh_pass: "{{ ansible_ssh_pass }}"
