---
- name: Use ssh-copy-id for all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Check if sshpass is installed
      command: which sshpass
      register: sshpass_check
      failed_when: false
      changed_when: false
      delegate_to: localhost

    - name: Install sshpass
      apt:
        name: sshpass
        state: present
      when: sshpass_check.rc != 0
      delegate_to: localhost

    - name: Copy SSH key using ssh-copy-id
      command: 
        cmd: sshpass -p '{{ ansible_ssh_pass }}' ssh-copy-id -o StrictHostKeyChecking=no {{ ansible_user }}@{{ inventory_hostname }}
      delegate_to: localhost
      ignore_errors: yes

