---
- hosts: rke2_servers
  tasks:
    - name: Download RKE2 kubeconfig to localhost
      ansible.builtin.fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: "{{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }}"
        flat: yes
      delegate_to: "{{ groups['rke2_servers'][0] }}"
      run_once: true

    - name: Replace loopback IP by master server IP
      ansible.builtin.replace:
        path: "{{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }}"
        regexp: '127.0.0.1'
        replace: "{{ groups['rke2_servers'][0] }}"
      delegate_to: localhost
      become: false

    - name: Prepare summary
      ansible.builtin.shell:
        cmd: "kubectl --kubeconfig {{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }} get nodes -o wide --show-labels"
      args:
        executable: /bin/bash
      changed_when: false
      delegate_to: localhost
      run_once: true
      retries: 5
      register: nodes_summary

    - name: K8s nodes state
      ansible.builtin.debug:
        var: nodes_summary.stdout_lines
      run_once: true

    - name: Check nodes state
      ansible.builtin.shell:
        cmd: "kubectl --kubeconfig {{ rke2_download_kubeconf_path }}/{{ rke2_download_kubeconf_file_name }} get nodes --no-headers"
      register: nodes_check
      delegate_to: localhost

    - name: Check if any node is NOT in the "Ready" state
      fail:
        msg: "Warning: One or more nodes are not in the Ready state."
      when: "'Ready' not in nodes_check.stdout"
      delegate_to: localhost
      run_once: true

    - name: Confirm RKE2 cluster is up and running
      ansible.builtin.debug:
        msg: "Your RKE2 cluster is now up and running."
      when: "'Ready' in nodes_check.stdout"
      delegate_to: localhost
      run_once: true
